language: objective-c
os:
- linux
- osx
sudo: false
branches:
  except:
  - /^v[0-9]/
env:
  matrix:
  - TRAVIS_NODE_VERSION="4.1"
  - TRAVIS_NODE_VERSION="4.2"
  - TRAVIS_NODE_VERSION="stable"
cache:
  directories:
  - node_modules
before_script:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- npm install -g npm
- npm install
- git config --global user.email "travis-ci-build@volusion.com"
- git config --global user.name "Travis CI Build"
script:
- node --version
- npm --version
- if [ -n "TRAVIS_TAG" ]; then npm run ci-build-stable; else npm run ci-build; fi
notifications:
  slack:
    secure: TR4XI9sDilkAwtjgGc84cuVNwfIuNZZUQHBKZCCCdkB/Ssso8U94aspkSrVhpbb9vW6KdXoaPV+lmoQ237F0hqChF3bHKFMfLTiZTUlP6SsIDYz5P8u39+CP/bW3y5ILfASDhPY/YReEL8kgjGNmkqzbB/3n7NbwgusA4dW7lI0NpZoHWbtZ5m3QfQ0Y5eQJZxvX6k3FnHpSvSKCcC8Q2iG+WPIGMnpRThA+YwzocEYNy1EP8JAQvGnDd8mnbskcSTn3E9j1UyeMM7EedN4fet3/l/zzQEF5oqYuVsua/xz9vxUSEhoMktYCgM664xv0R7HPZzu5pL9THmA0KPEhEob77oGKoGUN5ibBEgRRWCrRrFkBckLcagnFdAD/MggvAsZAcJdG0xRHyiegZfvpWm+yqE0OFgAw/JnW3fIrsKL5XMJ+UjKQhXovVqx83xBM81lTGT+12o8zUUC4lkpvfnvo3wDEQeCf65FMXCCm0B3ATKB4QAMNHarsxkYYmRWoo511NpJmJ1ay2KzEN47S/NV+Wnxh/2rV7ptdQvzpJ8fW1QTkiUyqQMsRHXtEZisiZc+78r6ZMjXgKQ/NrvDdZvPTXoZASkekmiC9ywPa/5aVnK4Ir5CD8+1tGQl56JWPs0N43uD6jFZZhD/P53+iO6wYPQomconR8bMxJjtih18=
