language: objective-c
os:
- linux
- osx
sudo: false
branches:
  except:
  - /^v[0-9]/
env:
  matrix:
  - TRAVIS_NODE_VERSION="4.1"
  - TRAVIS_NODE_VERSION="4.2"
  - TRAVIS_NODE_VERSION="stable"
cache:
  directories:
  - node_modules
before_script:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- npm install -g npm
- npm install
- git config --global user.email "travis-ci-build@volusion.com"
- git config --global user.name "Travis CI Build"
script:
- node --version
- npm --version
- if [ -n "TRAVIS_TAG" ]; then npm run ci-build-stable; else npm run ci-build; fi
notifications:
  slack:
    secure: soBunnVXYn3aZDs/n0VlmN+oHs+q3MMmJyQMU4b3+pAM0InuzdfEhGtYXo17GVvWf2+FfwLdNmnoZo4PtCZy2mESLVnW/SC57qZCdJM3fBxzimJYqec0JYQEd5mZk9I3ZGPLxNIowEUHMM3kbTZH3dp3O90Ev8/R+APk+0Lq9uARcTd365YDE4pAsc00NjkeDcYLJQ+QdOrn6s4xWo+ehILxgq2kVyAgPkhxnxgmbAOrFKVDqLlvLcJpuZIBfiTFGQP7yXI8AF9WmMFdzBi/0aMlG5QEztb0gREXcmy4hvU/k1Swii2iDwNDHbbw+W3MMC8CMEzU1WlN/tG1F0/Qy7YoOt3dkHh1OMd27ZirCq5sQkNicgqbBsDCPBU1zvam+aKU/cGjEANnCaecViF76OO8hhgpTBv3RuRnmuJEQ2XQ+uhH8HTo4jTOIGc/CuvL/46p1ap4wmnDr+i0zbyA+XqRa/dU8ynI6PQRGWi+OiPWqtsRo9SD3INHAxnKwaJ3ocfpmK3fxPwANN8nghZiivpeJctHbX0kIvAwzb6ZGktELjshFD53tbrDCUzrTqcF5T1g74tM9yJ1DXHQWuZcvClCYc9rNb/EB4YU7XoAyZ2+4Lig4LnU04JC0DdGt2QC9t5sCdiEREOjJ5hSCsh38LSEZn2Qv9WGVrtoRM2mfG8=
